---
- name: Add zrepl apt key
  apt_key:
    url: https://zrepl.cschwarz.com/apt/apt-key.asc
    state: present

- name: Add zrepl apt repository
  apt_repository:
    repo: deb https://zrepl.cschwarz.com/apt/debian {{ansible_distribution_release}} main

- name: Install zrepl
  apt:
    name: zrepl
    state: present
    update_cache: true

- name: Create zrepl config directory
  file:
    path: /etc/zrepl
    state: directory

- name: Place zrepl config file
  template:
    src: zrepl.yml.j2
    dest: /etc/zrepl/zrepl.yml

- name: Validate zrepl config
  command: zrepl configcheck

- name: Place zrepl-notify
  template:
    src: zrepl-notify.sh.j2
    dest: /usr/local/bin/zrepl-notify
    mode: 0755

- name: Place zrepl-kopia-uploader
  template:
    src: zrepl-kopia-uploader.sh.j2
    dest: /usr/local/bin/zrepl-kopia-uploader
    mode: 0755

- name: Place zrepl-kopia-uploader systemd service
  template:
    src: zrepl-kopia-uploader.service.j2
    dest: /etc/systemd/system/zrepl-kopia-uploader.service
  notify: Reload systemd daemon

- name: Place zrepl-kopia-uploader systemd timer
  template:
    src: zrepl-kopia-uploader.timer.j2
    dest: /etc/systemd/system/zrepl-kopia-uploader.timer
  notify: Reload systemd daemon
